name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-self-hosted:
    name: CI/CD (Self-Hosted Runner)
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          npm install

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Run frontend unit tests
        working-directory: frontend/src/tests
        run: npm -v
        env:
          CI: true

      - name: Build frontend application
        working-directory: frontend
        env: 
          CI: false
        run: npm run build

      - name: List build directory contents before uploading
        run: Get-ChildItem -Force ./frontend/build/

      - name: Verify frontend build artifacts
        if: success()
        run: |
          if (-Not (Test-Path "./frontend/build")) {
            Write-Host "Build artifacts not found!"
            exit 1
          }

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: frontend/build/**

  lint-ubuntu:
    name: CI/CD (Ubuntu Runner)
    runs-on: ubuntu-latest
    needs: lint-self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Install dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Run frontend unit tests
        working-directory: frontend/src/tests
        run: npm test
        env:
          CI: true

      - name: Build frontend application
        working-directory: frontend
        env: 
          CI: false
        run: npm run build

      - name: List build directory contents before uploading
        run: ls -la ./frontend/build/

      - name: Verify frontend build artifacts
        if: success()
        run: |
          if [ ! -d "./frontend/build" ]; then
            echo "Build artifacts not found!"
            exit 1
          fi

      - name: Archive production artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: production-artifacts
          path: frontend/build/**
